### ISSUE TITLE
Expanded documentation on SSURGO functionality

### ISSUE THREAD

**Issue by kevinwolz** [ropensci/FedData#55] opened 2020-04-27 19:08 UTC
I'm wondering if you have any expanded documentation/examples/scripts that illustrate how to actually plot maps of SSURGO variables of interest after downloading the data using `get_ssurgo()`. I realize that actually doing things with the data, beyond just downloading it, is beyond the scope of FedData. However, it's unclear to me how the resulting structure of the SSURGO data output by `get_ssurgo()` plays with other common analysis/mapping methods. Even just pointing to some examples from others and saying that "the output `get_ssurgo()` works the same way as if you were doing it their way or getting the data thay way" would be really helpful.

**Comment by dylanbeaudette** [comment] 2020-04-27 19:34
This is a good question. Most of the tabular data (e.g. drainage class, hydrologic group, pH, water holding capacity) form a many:one relationship with the spatial data. Tabular and spatial data are linked by the `mukey`, but, you cannot just join the tables. Data must be aggregated using according to the intended purpose of analysis or research question. For example, if you were interested in making a thematic map of soil pH within the top 10cm you would have to:

 1. perform a horizon-thickness weighted mean pH for each component by map unit
 2. select a representative component or perform weighted mean pH over all components
 3. join aggregated values to spatial data

**Comment by bocinsky** [comment] 2020-04-27 19:38
Dylan's right... these aren't simple data! However it would be good nonetheless to have some extended documentation, perhaps in the form of a vignette. I'll think about how to develop one... but in the meantime, @kevinwolz , if you end up doing a particular analysis using the SSURGO data that you think would be useful to others perhaps we could drop it in as a vignette?

**Comment by kevinwolz** [comment] 2020-04-27 20:00
_Someone_ needs to create a comprehensive R package for extracting and aggregating SSURGO data. That won't be me, but I would certainly use the heck out of it! Ideally, this package would remove the need to know so much about SQL in order to effectively utilize SSURGO data. 

FedData is the best tool that I know of for easily getting SSURGO data (and many other datasets we work with) into R - certainly better than soilDB. Beyond that, though, SSURGO is just one complex, messy beast.

The frustrating thing is that I feel like most scientists (at least here in the biology realm) only utilize a very small percentage of all the variables in SSURGO and are only typically doing so at the mukey level. So, all the complex aggregation of components/horizens, and the three steps @dylanbeaudette mentioned, are just a barrier that shouldn't need to be recreated every time someone wants to use the most common data. 

It looks like ESRI has attempted to remove the aggregation barrier by creating [this](https://www.arcgis.com/home/item.html?id=cdc49bd63ea54dd2977f3f2853e07fff), though of course ArcGIS is beyond a paywall. Similarly, here is some R code from UC Davis on dealing with the SSURGO data aggregation issue. I think this code is the foundation of the three steps that @dylanbeaudette mentioned and could be the foundation of some more user-friendly functions to handle SSURGO data.

My group will potentially be doing a lot of this over the next year, and we're happy to share whatever is helpful, though no promises that whatever we create will be fully optimized. I'll stop rambling now, but would love to keep this conversation going...R tools for SSURGO are desperately needed!

**Comment by dylanbeaudette** [comment] 2020-04-27 20:57
@kevinwolz SSURGO was created by soil scientists for soil scientists. There is a ton of documentation in the form of manuals and articles in the literature. See over 15 years of articles in both SSSAJ and Geoderma, some by this author. There are a number of paths forward, including some of the ideas + code offered at:

 * https://github.com/ncss-tech/
 * http://ncss-tech.github.io/AQP/

A cook-book approach might make sense for a limited subset of attributes, but apart from some generic examples there are just too many use cases, considerations, and data elements to offer a comprehensive "how to" guide. I'd suggest working with a soil scientist in your area or institution as a first step. 

As a contributor to this package and author of `soilDB` I don't see how the two possibly overlap enough for a value judgement. Please take some time to read the documentation and collaborate with a subject matter expert. I would do the same before attempting to integrate one of the many biological databases into my work.

I've added some old but still relevant presentations on the subject here:
https://github.com/ncss-tech/ncss-tech.github.io/tree/master/SSURGO

We (USDA-NRCS) are in the process of writing some new R functionality for interaction with SSURGO (SDA, gSSURGO, standard SSURGO, and more).

**Comment by bocinsky** [comment] 2020-04-27 20:58
A good place to start might be clean R scripts for extracting the variables in gSSURGO. I've templated much of that code, but what I can say is that the current version of FedData doesn't make it very easy, mainly due to use of the legacy `sp` data structures. Here is a quick example of how to do steps 2 and 3 of @dylanbeaudette 's example. Note that I convert the get_ssurgo output to a Simple Features (`sf`) object, which makes the aggregation much easier.

``` r
library(FedData)
#> Loading required package: magrittr
#> Loading required package: sf
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
#> Loading required package: sp
library(ggplot2)

WI025 <- get_ssurgo(template = "WI025", 
                    label = "WI_TEST")
#> (Down)Loading SSURGO data for survey area 1 of 1: WI025
#> Downloading file: http://websoilsurvey.sc.egov.usda.gov/DSD/Download/Cache/SSA/wss_SSA_WI025_[2019-09-10].zip
#> Merging all SSURGO Map Unit polygons
#> Merging all SSURGO data tables

# Convert mapunit polygons to simple features
WI025$spatial %<>%
  sf::st_as_sf() %>%
  dplyr::mutate(MUKEY = as.character(MUKEY))

# Aggregate the "slope.r" (slope) variable across 
# components within each mapunit. This takes the 
# weighted average by component percent. It assumes
# components with a "slope.r" of NA are zero.
WI025_slopes <- 
  WI025$tabular$component %>%
  dplyr::mutate(
    # Make "MUKEY" a character version of "mukey"
    MUKEY = as.character(mukey),
    # Replace slopes of NA with "0"
    slope.r = tidyr::replace_na(slope.r, 0)
  ) %>%
  dplyr::group_by(MUKEY) %>%
  dplyr::summarise(slope.r = sum((comppct.r/100) * slope.r, na.rm = T)) %>%
  dplyr::right_join(WI025$spatial) %>%
  dplyr::arrange(-slope.r) %>%
  sf::st_as_sf()
#> Joining, by = "MUKEY"

# Plot slopes >= 30º
WI025_slopes %>%
  dplyr::filter(slope.r >= 30) %>%
  ggplot(aes(fill = slope.r)) +
  geom_sf(color = NA)
```

![](https://i.imgur.com/P6eWv85.png)

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bocinsky** [comment] 2020-04-27 21:11
I'd also second @dylanbeaudette that there is little overlap between `soilDB` and `FedData`. `FedData` aims at relatively high-level, rapid, and reproducible access to many different federated datasets.  `soilDB` (and `app`) allows for much lower-level data access, and tools for professional soil scientists (which I'm most definitely *not*).

I like your ideas of including gSSURGO access in `FedData`, and would be interested in pursuing a package that included the algorithms in R for deriving gSSURGO from the SSURGO data.

**Comment by bocinsky** [comment] 2020-04-27 21:45
Looks like what we'll really want is the new [gNATSGO](https://nrcs.app.box.com/v/soils/file/643765519602) database, and the definitions of the Valu1 table.

**Comment by bocinsky** [comment] 2020-04-27 21:59
... and the gridded data in both gNATSGO and gSSURGO are within file geodatabases, and so far as I know can't be retrieved using GDAL. We might be SOL for accessing the gridded data. @dylanbeaudette, do you know if someone has published scripts for calculating the valu1 table? Field definitions are here: https://prod.nrcs.usda.gov/Internet/FSE_DOCUMENTS/nrcs142p2_052165.pdf

**Comment by jneme910** [comment] 2020-04-27 23:15
http://github.com/ncss-tech/ssurgoOnDemand/archive/master.zip

**Comment by jneme910** [comment] 2020-04-27 23:16
https://www.nrcs.usda.gov/wps/PA_NRCSConsumption/download?cid=nrcseprd1496615&ext=zip

**Comment by dylanbeaudette** [comment] 2020-04-28 04:24
I'd rather not re-implement the `valu1` table as-is, there has been much internal consternation about the exact methods. @jneme910 and Charles Ferguson have done much of the work in SQL run against the data in SDA. Those queries are the place to start. Similar work has been done in python by Steve Peaslee.

**Comment by dylanbeaudette** [comment] 2020-05-01 15:42
I've let several of my colleagues know about the interest and we will be posting some new content soon. I'm keen to close the issue unless you see anything else here that needs to be addressed, @bocinsky ?

**Comment by bocinsky** [comment] 2020-05-01 15:52
Sounds good, and I'll be interested to hear from y'all! Hope all is well. Closing now.

**Closed by bocinsky** 2020-05-01 15:52 UTC

**Comment by kevinwolz** [comment] 2020-05-03 14:12
Thanks, all. Some great info here, especially your example code @bocinsky . Thanks for that! I've never worked with simple features before, but they seem key to making the work flow much simpler. I'm going to look into those now. 

Point taken about `FedData` and `soilDB` having different purposes. Since I'm not a soil scientist, it's clear why `soilDB` overwhelms me!

I found [this great tutorial](https://r-forge.r-project.org/scm/viewvc.php/*checkout*/docs/soilDB/gSSURGO-SDA.html?revision=705&root=aqp) by @dylanbeaudette on how to work with gSSURGO data in R. The only catch is that it starts with a gSSURGO chunk distributed with `soilDB`. It doesn't address actually importing the gSSURGO raster, but does say: "Typically, gSSURGO data will be loaded from some kind of raster format such as GeoTIFF."

So, since (as @bocinsky said) gNATSGO and gSSURGO are distributed within file geodatabases that are seemingly inaccessible directly via R, how do I/we get from the raw state file downloaded from the geospatial data gateway to a GeoTIFF that R can import and utilize using @dylanbeaudette 's tutorial?

**Comment by kevinwolz** [comment] 2020-05-03 14:22
For what it's worth, [here](https://github.com/jsta/gssurgo) is a python package that seems to do handle the full gSSURGO workflow. It relies on the `arcpy` python package for the import step.
