### ISSUE TITLE
get_nlcd() performs projection transformation that is unexpected.

### ISSUE THREAD

**Issue by khurley-usgs** [ropensci/FedData#119] opened 2024-10-08 16:11 UTC
When downloading NLCD, the bounding box of the template does not match the bounding box of the returned data. This seems to be caused by a projection transformation of the template, resulting in an unexpected area of data returned by the function.

Repex:

```r
devtools::install_version(
  "FedData", 
  version = "4.0.0", 
  repos = "http://cran.us.r-project.org"
)
library(FedData)
library(ggplot2)
library(maps)

md_map <- maps::map(
    database = "state", 
    regions = "maryland", 
    fill = TRUE, 
    plot = FALSE
)

md_map <- sf::st_as_sf(md_map)
nlcd <- FedData::get_nlcd(
  template = md_map, 
  label = "md_nlcd", 
  year = 2019, 
  dataset = "landcover", 
  force.redo = FALSE
)

p <- ggplot(data = md_map) + 
  tidyterra::geom_spatraster(
    data = nlcd
  ) + 
  geom_sf(
    fill = "transparent", 
    linewidth = 1
  )
p
``` 

In the figure, the bounding box points of `nlcd` do not match the bounding box points of `md_map`. Looking at the `get_nlcd()` function, I believe this arises when the template has the projection transformed:

```r
template %<>% sf::st_transform("+proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs") %>% 
      sf::st_bbox()
```

**Comment by bocinsky** [comment] 2024-11-05 16:19
Hi there! Sorry for the delayed response. What you are seeing is by design. The bounding box gets defined in the NLCD projection system (that long PROJ string in your comment). FedData returns data in the native CRS and resolution of each dataset, leaving it up to the user to re-project or otherwise transform the output to meet their needs. One thing you could consider would be using `terra::mask` for a prettier map.

Closing.

**Closed by bocinsky** 2024-11-05 16:19 UTC
